[buildPlans.iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka.variants]
  inherits = "ss15"

    [buildPlans.iosevka.variants.design]
    eszet = "longs-s-lig-tailed"
    lower-lambda = "straight-turn"
    zero = "slashed"
    dollar = "through"
    bar = "natural-slope"
    lig-ltgteq = "slanted"
    punctuation-dot = "round"
    diacritic-dot = "round"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"

  [buildPlans.iosevka.ligations]
  inherits = "haskell"

[buildPlans.iosevka-slab]
family = "Iosevka Slab"
spacing = "normal"
serifs = "slab"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-slab.variants]
  inherits = "ss15"

    [buildPlans.iosevka-slab.variants.design]
    eszet = "longs-s-lig-tailed"
    lower-lambda = "straight-turn"
    zero = "slashed"
    dollar = "through"
    bar = "natural-slope"
    lig-ltgteq = "slanted"
    punctuation-dot = "round"
    diacritic-dot = "round"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"

  [buildPlans.iosevka-slab.ligations]
  inherits = "haskell"