[buildPlans.iosevkalyteterm]
family = "IosevkaLyteTerm"
spacing = "fontconfig-mono"
serifs = "sans"
export-glyph-names = true

[buildPlans.iosevkalyteterm.ligations]
inherits = "dlig"
disables = [ "exeqeqeq", "exeqeq", "exeqeq-dl", "exeq", "ineq", "connected-underscore", "connected-tilde-as-wave" ]

[buildPlans.iosevkalyteterm.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevkalyteterm.weights.book]
shape = 450
menu  = 450
css   = 450

[buildPlans.iosevkalyteterm.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevkalyteterm.weights.black]
shape = 900
menu  = 900
css   = 900

# [[buildPlans.iosevkalyteterm.compatibility-ligatures]]
# unicode = 57600 # 0xE100
# featureTag = 'calt'
# kequence = '<*>'

[buildPlans.iosevkalyteterm.variants]
inherits = "ss01"

[buildPlans.iosevkalyteterm.variants.design]
capital-a = 'curly-serifless'
capital-b = 'standard-interrupted-serifless'
capital-c = 'unilateral-inward-serifed'
capital-d = 'standard-serifless'
capital-g = 'toothless-rounded-inward-serifed-hooked'
capital-i = 'serifed'
capital-j = 'serifed'
capital-k = 'curly-serifless'
capital-l = 'motion-serifed'
capital-m = 'hanging'
capital-n = 'asymmetric'
capital-p = 'open'
capital-q = 'crossing'
capital-r = 'standing-open'
capital-s = 'unilateral-inward-serifed'
capital-t = 'motion-serifed'
capital-u = 'toothless-corner'
capital-v = 'curly'
capital-w = 'curly'
capital-x = 'curly-serifless'
capital-y = 'curly-base-serifed'
capital-z = 'curly-top-serifed-with-crossbar'
a = 'double-storey-toothless-corner'
b = 'toothless-corner'
c = 'unilateral-inward-serifed'
d = 'toothless-corner-serifless'
e = 'rounded'
f = 'flat-hook-tailed'
# g = 'double-story-open'
g = 'single-storey-earless-corner-flat-hook'
h = 'tailed'
i = 'tailed-serifed'
j = 'serifed'
k = 'curly-serifless'
l = 'tailed-serifed'
m = 'tailed'
n = 'earless-corner-tailed'
p = 'earless-corner'
q = 'earless-corner-tailed'
r = 'earless-corner'
s = 'unilateral-inward-serifed'
t = 'flat-hook'
u = 'toothless-corner'
v = 'curly'
w = 'curly'
x = 'curly-serifless'
y = 'curly-turn'
z = 'curly-top-serifed-with-crossbar'
# cyrl-capital-ze = 'unilateral-inward-serifed'
zero = 'slashed-split'
one = 'base-flat-top-serif'
two = 'curly-neck'
three = 'two-arcs'
four = 'semi-open-non-crossing'
five = 'vertical-upper-left-bar'
six = 'straight-bar'
seven = 'curly-crossbar-serifed'
eight = 'two-circles'
nine = 'straight-bar'
tilde = 'low'
asterisk = 'penta-low'
underscore = 'above-baseline'
pilcrow = 'low'
caret = 'low'
paren = 'flat-arc'
brace = 'curly-flat-boundary'
number-sign = 'upright-open'
ampersand = 'upper-open'
at = 'threefold-tall'
dollar = 'interrupted'
cent = 'open'
percent = 'rings-segmented-slash'
bar = 'force-upright'
ascii-single-quote = 'raised-comma'
ascii-grave = 'straight'
question = 'smooth'
punctuation-dot = 'round'

[buildPlans.iosevkalyteweb]
family = "IosevkaLyteWeb"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevkalyteweb.ligations]
inherits = "dlig"

[buildPlans.iosevkalyteweb.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevkalyteweb.weights.book]
shape = 450
menu  = 450
css   = 450

[buildPlans.iosevkalyteweb.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevkalyteweb.weights.black]
shape = 900
menu  = 900
css   = 900

[buildPlans.iosevkalyteweb.variants]
# inherit iosevkalyte?
inherits = "ss01"

[buildPlans.iosevkalyteweb.variants.design]
cv01 = 2
cv02 = 7
cv03 = 4
cv07 = 24
cv10 = 2
cv11 = 2
cv12 = 2
cv14 = 2
cv15 = 2
cv16 = 4
cv17 = 6
cv18 = 4
cv19 = 2
cv21 = 2
cv22 = 2
cv23 = 2
cv24 = 4
cv25 = 23
cv27 = 2
cv28 = 4
cv29 = 2
cv31 = 3
cv32 = 6
cv33 = 1
cv34 = 8
cv35 = 6
cv36 = 2
cv37 = 8
cv38 = 5
cv39 = 3
cv40 = 2
cv41 = 2
cv42 = 13
cv43 = 4
cv45 = 2
cv46 = 2
cv47 = 2
cv48 = 2
cv49 = 4
cv50 = 24
cv58 = 4
cv71 = 4
cv72 = 2
cv73 = 2
cv74 = 2
cv75 = 4
cv76 = 2
cv77 = 3
cv78 = 12
cv79 = 2
cv80 = 3
cv81 = 2
cv82 = 2
cv83 = 1
cv85 = 3
cv86 = 2
cv87 = 2
cv88 = 1
cv89 = 2
cv90 = 3
cv91 = 3
cv92 = 3
cv93 = 2
cv95 = 1
cv96 = 2
cv97 = 1
cv98 = 1
cv99 = 1
